### ISSUE TITLE
Icon on Mac Os Dock

### ISSUE THREAD

**Issue by pj1234678** [Sogomn/Ratty#4]
I think we can fix it with the line
System.setProperty("apple.awt.UIElement", "true");

**Comment by Sogomn** [comment]
What exactly is the problem?

**Comment by pj1234678** [comment]
The Java Icon is displayed in the dock of a mac when the client is running.

**Comment by Sogomn** [comment]
Didn't know that, thanks. Make a pull request if you have a solution.

**Comment by pj1234678** [comment]
A Hacked up solution I found would be the client restarting the Jar file with a flag in the JVM then Closing the original instance.
